version: '3.1'

services:
  back-music:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: dev
    ports:
      - '8084:8084'

networks:
  default:
    external:
      name: connect-default