<<<<<<< HEAD
server:
  port: 8084

spring:
  application:
    name: music

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
=======
spring:
  config:
    import: optional:configserver:http://throwng:458859@localhost:8088
  application:
    name: music
  profiles:
    active: dev
>>>>>>> ba89da3ff349afec5bb62d148d7a6e24d4604ae2
