server:
  port: 8084

spring:
  application:
    name: music

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  datasource:
    url: jdbc:mysql://localhost:3306/throwng?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: throwng
    password: throwng577899

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
