server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          predicates:
            - Path=/users/user/**
          uri: lb://USER
          sensitive-headers: Cookie,Set-Cookie
          #filters:
          #  - CustomAuthFilter
        - id: user
          predicates:
            - Path=/users/auth/**
          uri: lb://USER
          sensitive-headers: Cookie,Set-Cookie
        - id: quiz
          predicates:
            - Path=/quizzes/**
          uri: lb://QUIZ
          sensitive-headers: Cookie,Set-Cookie
          #filters:
           # - CustomAuthFilter
        - id: music
          predicates:
            - Path=/music/**
          uri: lb://MUSIC
          #uri: http://localhost:8084/
          sensitive-headers: Cookie,Set-Cookie
          #filters:
           # - CustomAuthFilter
        - id: notification
          predicates:
            - Path=/notifications/**
          uri: lb://NOTIFICATION
          sensitive-headers: Cookie,Set-Cookie
          #filters:
           # - CustomAuthFilter

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
